### ISSUE TITLE
Prompt in LM Studio?

### ISSUE THREAD

**Issue by zinwelzl** [ZySec-AI/ZySec#4]
Hi.

Should I put any prompt in LM Studio for web penest, or network pentest, etc.

Or it doesn't matter?

**Comment by venkycs** [comment]
You need to have ZySec and Security keyword in LM studio, this will helps to get certain layers activated. Please take it from configuration page python script of the code.

**Comment by venkycs** [comment]
https://huggingface.co/ZySec-AI/ZySec-7B-GGUF
@zinwelzl
